"""empty message

Revision ID: 5364d07b607b
Revises: 
Create Date: 2024-01-18 17:18:52.641081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5364d07b607b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('writer', sa.VARCHAR(length=30), nullable=False),
    sa.Column('title', sa.VARCHAR(length=30), nullable=False),
    sa.Column('content', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('del_yn', sa.VARCHAR(length=1), nullable=False),
    sa.PrimaryKeyConstraint('no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board')
    # ### end Alembic commands ###
